[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
crossterm = "0.29.0"
tokio = { version = "1.46.1", features = ["io-util", "net", "rt"] }
common = {path = "../common"}
serde_json = "1.0.140"
