[package]
name = "snakecli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.40"
colored = "3.0.0"
crossterm = "0.29.0"
rand = "0.9.1"
serde = { version = "1.0.219", features = ["serde_derive"] }
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["full"] }
